# -*- coding: utf-8 -*-
"""Actividad7+AixaAlvarez-G3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13wtFwaNmj2zTBmLfnFGNHwwb39BeJ9fl
"""

class Mamifero:
  def __init__(self, cantMamas, esperanzaDeVida):
    self.cant_mamas=cantMamas
    self.esperanza_de_vida=esperanzaDeVida

  def mamar(self):
    if self.cant_mamas!=0:
      return f"puede mamar."
    else:
      return f"no es mamífero"  

  def nacer(self):
    return f"es vivíparo."

class AnimalMarino:
  def __init__(self, tieneBranquias, especie):
    self.tiene_branquias=tieneBranquias
    self.especie=especie

  def nadar(self):
    return f"puede nadar."

class Cetaceo(Mamifero,AnimalMarino):
  def __init__(self, cantMamas, esperanzaDeVida, tieneBranquias, especie, notas, viveEn, peso):
    
    Mamifero.__init__(self, cantMamas, esperanzaDeVida)
    AnimalMarino.__init__(self, tieneBranquias, especie)

    self.notas=notas
    self.vive_en=viveEn
    self.peso=peso

  def __str__(self):
    return f"La/El {self.especie} es un animal que vive {self.vive_en}. Viven aproximadamente {self.esperanza_de_vida}.\nAdemás, pesan {self.peso}, tienen {self.tiene_branquias} branquias y cuentan con {self.cant_mamas} mamas.\nTambién son conocidas/os como {self.notas}"

orca = Cetaceo(2,"50 años","0","Orca","delfínido grande", "bajo el agua", "entre 4000 y 5600 kg")
print(f"{orca}")
print(f"Este cetáceo {orca.nacer()}")
print(f"Este cetáceo {orca.nadar()}")